### ISSUE TITLE
The repository is out of date

### ISSUE THREAD

**Issue by ghost** [LI-COR/eddypro-engine#2]
Dear all,
Any plans to release the code for the new version you are distributing (7.0.4)?

**Comment by davidaguilerar** [comment]
I agree with that.

**Comment by kebasaa** [comment]
It seems like they've abandoned their open source efforts. Pity. Especially for us Linux users

**Comment by ankurdesai** [comment]
As someone who runs nearly a frozen flux towers with automated nightly flux processing and uploading on Linux servers, I really appreciate the work in providing this code, which my lab relies on. Please keep updating it. Or provide a licensed version. What we do can not be replicated with SmarFlux embedded OS -or- with Windows.

**Comment by geryatejina** [comment]
Sorry for seemingly abandoning the repo, my bad. As you may be aware, there has been a change in the license starting from EddyPro 7.0.0 (please familiarize yourself with the license change if you haven't). However, the software is still open-source for academic use and this repo shall keep the `master` branch available to the community. 
I've now updated the code and tags. Let me know if you need anythings else and again, apologies for the long delay.

**Comment by mcuntz** [comment]
I updated the code:
```
eddypro-engine> git pull
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 39 (delta 25), reused 39 (delta 25), pack-reused 0
Unpacking objects: 100% (39/39), 3.83 KiB | 139.00 KiB/s, done.
From https://github.com/LI-COR/eddypro-engine
   54f2014..fcf17a3  master            -> origin/master
 * [new tag]         smartflux2-2.2.16 -> smartflux2-2.2.16
 * [new tag]         v7.0.3            -> v7.0.3
 * [new tag]         v7.0.6            -> v7.0.6
Updating 54f2014..fcf17a3
Fast-forward
 CHANGELOG                           | 13 ++++++++++++-
 src/src_common/version_and_date.inc |  4 ++--
 src/src_fcc/init_out_files.f90      |  2 +-
 src/src_fcc/write_out_full_fcc.f90  | 14 +++++++-------
 src/src_rp/init_outfiles_rp.f90     |  2 +-
 5 files changed, 23 insertions(+), 12 deletions(-)
```

And then tried to compile it as given in the README.md but it fails:
```
> cd eddypro-engine/
> cd prj/
> make rp
Compiling for Mac OS
gfortran -Wall -pedantic -fall-intrinsics -fbounds-check -Wextra -Wcharacter-truncation -Wunderflow -Wno-compare-reals -std=f2008 -O3 -I ../obj/mac/ -c ../src/src_common/m_libdate.f90 -o ../obj/mac/m_libdate.o
...
gfortran -Wall -pedantic -fall-intrinsics -fbounds-check -Wextra -Wcharacter-truncation -Wunderflow -Wno-compare-reals -std=f2008 -O3 -I ../obj/mac/ -c ../src/src_rp/eddypro-rp_main.f90 -o ../obj/mac/eddypro-rp_main.o
../src/src_rp/eddypro-rp_main.f90:1557:92:

 1557 |                 if (EddYProProj%out_fluxnet) call WriteOutFluxnetOnlyBiomet(suffixOutString)
      |                                                                                            1
Error: More actual than formal arguments in procedure call at (1)
../src/src_rp/eddypro-rp_main.f90:1608:92:

 1608 |                 if (EddyProProj%out_fluxnet) call WriteOutFluxnetOnlyBiomet(suffixOutString)
      |                                                                                            1
Error: More actual than formal arguments in procedure call at (1)
../src/src_rp/eddypro-rp_main.f90:1624:92:

 1624 |                 if (EddYProProj%out_fluxnet) call WriteOutFluxnetOnlyBiomet(suffixOutString)
      |                                                                                            1
Error: More actual than formal arguments in procedure call at (1)
../src/src_rp/eddypro-rp_main.f90:1640:92:

 1640 |                 if (EddYProProj%out_fluxnet) call WriteOutFluxnetOnlyBiomet(suffixOutString)
      |                                                                                            1
Error: More actual than formal arguments in procedure call at (1)
../src/src_rp/eddypro-rp_main.f90:1733:92:

 1733 |                 if (EddYProProj%out_fluxnet) call WriteOutFluxnetOnlyBiomet(suffixOutString)
      |                                                                                            1
Error: More actual than formal arguments in procedure call at (1)
../src/src_rp/eddypro-rp_main.f90:1806:92:

 1806 |                 if (EddYProProj%out_fluxnet) call WriteOutFluxnetOnlyBiomet(suffixOutString)
      |                                                                                            1
Error: More actual than formal arguments in procedure call at (1)
../src/src_rp/eddypro-rp_main.f90:1928:42:

  710 |                 call TiltCorrection('double_rotation', .false., E2Set, &
      |                                                       2
......
 1928 |             call TiltCorrection(Meth%rot, GoPlanarFit, E2Set, &
      |                                          1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
make: *** [eddypro-rp_main.o] Error 1
```

due to the same reason as given in [#3](https://github.com/LI-COR/eddypro-engine/issues/3):
WriteOutFluxnetOnlyBiomet is defined without argument in src/src_rp/write_out_fluxnet_only_biomet.f90:
line 41: subroutine WriteOutFluxnetOnlyBiomet()

**Comment by geryatejina** [comment]
HI Matthias,
you're using a more recent version of gfortran than I have installed on my older MBP. I may upgrade my fairly old gfortran version and look for a fix, but please note that this repo only contains code only for the `main` branch, which gets updated only at the time of a new release. Long story short, for using any fix I make now you'd have to wait until next release. 
As an alternative, you may try to downgrade gfortran to a previous version (I am using gcc version 8.1.0 ), which will compile just fine. If instead you need to keep your gfortran current for other reasons, you may try to describe the problem you have with spectral corrections. Chances are that's already fixed in my most current `dev` branch and I could give you an executable with that fix. Let me know what you prefer.

**Comment by mcuntz** [comment]
Hey Gerardo,

I installed gcc@8 with homebrew and used gfortran-8 for compilation, which worked fine.

I will investigate the spectral correction problem, which I really cannot describe you right now because it is very opaque to us. I will give you an update once I had time to investigate (the engineer downgraded to the version 6.2.2 for the time being).

Kind regards
Matthias

**Comment by geryatejina** [comment]
Ok, good to hear that worked. Let me know if you need a hand with the spectral correction thing. In the meantime I'll update my gfortran and see if I can fix the new compilation issues.
I am going to close this issue, as this concerns updating the repo, and open another issue for the compilation error.

**Comment by nealmcb** [comment]
> the software is still open-source for academic use

There is no such thing. There is [source-available](https://en.wikipedia.org/wiki/Source-available_software), but restrictions to e.g. "non-commercial academic or government research only" is not allowed under the [definition of open source – Open Source Initiative](https://opensource.org/osd).
In addition, the licensing of this software is very confusing and potentially illegal. There is both a License file and a License.txt file, the latter noting that some of the software here is GPL. But there are severe restrictions on combining GPL code with other functionality.
See #10

**Comment by jkittner** [comment]
> However, the software is still open-source for academic use and this repo shall keep the master branch available to the community.

Is this still true? There hasn't been an update in quite a while and the tags are also not up-to-date. I am also trying to build this for ubuntu 22.04. Rebasing the open PR for linux support onto the master branch did make it compile, but there are a few issues. And the latest version would also be nice!
