### ISSUE TITLE
Tmp file directory nonexistant

### ISSUE THREAD

**Issue by acebulsk** [LI-COR/eddypro-engine#7]
I having trouble running eddypro-engine on my linux machine (ubuntu 22.04) with this command:

`eddypro_rp -s linux eddy-pro-cmd/3m.eddypro`

Which returns this:

```
 *******************
  Executing EddyPro 
 *******************

 Reading EddyPro project file: eddy-pro-cmd/3m.eddypro..
 Done.
sh: 1: cannot create ../tmp/tmp_2022-10-24T171406788/flist.tmp: Directory nonexistent
  Fatal error(86)> Could not retrieve files from directory. Either directory does not exist
  Fatal error(86)> or it does not contain files matching the selected requirements.
  Fatal error(86)> Program execution aborted.
STOP 1
```
Any ideas?

Attached are my .eddypro and .metadata files. 

Cheers.

[eddypro_files.zip](https://github.com/LI-COR/eddypro-engine/files/9855955/eddypro_files.zip)

**Comment by ChristopheC-inrae** [comment]
You must create "tmp" dir in the dir "eddypro-engine"
You must also install  p7zip-full to read ghg file 
sudo apt install  p7zip-full (debian 10)

**Comment by acebulsk** [comment]
This worked, thanks!
